import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SmartAudit - An AI powered smart contract auditor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="text-white" style={{ fontFamily: "" }}>
            <Providers>
              {children}
              </Providers>
          </main>
        </body>
      </html>
    </ClerkProvider>
  ); 
}  